name: Compile & Test Changed or New Files

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Build Project
    runs-on: ubuntu-latest
    env:
      INFURA_KEY: my-infura-key-here
      GAS_PRICE_GWEI_KEY: 20
      GAS_WEI_KEY: 2500000
      MNEMONIC_KEY: my-mnemonic-value-here
      ADDRESS_COUNT_KEY: 5
      DEFAULT_ADDRESS_INDEX_KEY: 0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.x'
      - name: Install dependencies
        run: |
          yarn install
      - name: Compiling Smart Contracts
        run: |
          ./node_modules/.bin/truffle compile
      - name: Test Changes or New Files
        run: |
          git remote add origin git@github.com:teller-protocol/teller-protocol-v1
          yarn test:coverage `git diff --name-only origin/develop -- test/ | tr '\n' " "`
