name: Compile & Test Changed or New Files

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Build Project
    runs-on: ubuntu-latest
    env:
      INFURA_KEY: my-infura-key-here
      GAS_PRICE_GWEI_KEY: 20
      GAS_WEI_KEY: 2500000
      MNEMONIC_KEY: my-mnemonic-value-here
      ADDRESS_COUNT_KEY: 5
      DEFAULT_ADDRESS_INDEX_KEY: 0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.x'
      - name: Install dependencies
        run: |
          yarn install
      - id: files
        name: Get List of Changed Files
        uses: jitterbit/get-changed-files@v1
      - name: Test Changed Files
        env:
          CHANGED_FILES: "${{ steps.files.outputs.all }}"
        run: |
          echo $CHANGED_FILES
          yarn test `echo $CHANGED_FILES | tr " " '\n' | grep 'test/' | tr '\n' " "`
